modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="dedsafio3"
version="0.0.9"
displayName="dedsafio3"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dedsafio-3-fan-proyect"
logoFile="logo.png"
credits="Crafted for fans by fans/ Creditos a: @m0ch1dmc, @imaim12345, @._2ian2_., @leoooohg, @cyclicaal"
authors="Pakinhop, ForzakenNeon"
description="A fan-made mod for Minecraft inspired by Dedsafio 3, a popular hardcore Minecraft series. The goal is to replicate and integrate unique mechanics from the series into the game, providing fans with an immersive experience that captures the intense survival challenges of Dedsafio 3. The mod aims to faithfully recreate key features and elements that define the series' gameplay, such as specialized difficulty settings, unique progression systems, and any exclusive items or abilities seen in the episodes."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.dedsafio3]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.dedsafio3]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration